language: ruby
sudo: required
dist: trusty
cache: bundler

matrix:
  include:
    - rvm: 2.1.10
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
    - rvm: jruby-1.7.26
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
    - rvm: rbx-3.60
  allow_failures:
    - rvm: rbx-3.60

addons:
  code_climate:
    repo_token: cd7df1b0973b1b3323ce8b2f09fe9c087010115889fed6
  # https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
  # https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
  apt:
    packages:
    - haveged
